config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy!

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :preco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atividade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, class: "form-label" %>
    <%= form.text_field :nome, class: "form-input" %>
  </div>

  <div>
    <%= form.label :descricao, class: "form-label" %>
    <%= form.text_field :descricao, class: "form-input" %>
  </div>

  <div>
    <%= form.label :preco, class: "form-label" %>
    <%= form.text_field :preco, class: "form-input" %>
  </div>

  <div>
    <%= form.submit "Save", class: "submit-button" %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>" class="product-container">
  <p class="product-detail">
    <span class="product-label"><strong>Nome:</strong></span>
    <span class="product-value"><%= produto.nome %></span>
  </p>

  <p class="product-detail">
    <span class="product-label"><strong>Descrição:</strong></span>
    <span class="product-value"><%= produto.descricao %></span>
  </p>

  <p class="product-detail">
    <span class="product-label"><strong>Preço:</strong></span>
    <span class="product-value"><%= produto.preco %></span>
  </p>
</div>

app/views/produtos/edit.html.erb
<h1 class="page-title">Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Show this produto", @produto, class: "link back-button" %> |
  <%= link_to "Back to produtos", produtos_path, class: "link back-button" %>
</div>

app/views/produtos/index.html.erb
<h1>Produtos</h1>

<div id="produtos">
  <% @produtos.each do |produto| %>
    <%= render produto %>
    <p>
      <%= link_to "Show this produto", produto, class: "link back-button" %>
    </p>
  <% end %>
</div>

<%= link_to "New produto", new_produto_path, class: "link back-button" %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Back to produtos", produtos_path, class: "link back-button" %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="produto-container">
  <%= render @produto %>
</div>

<div>
  <%= link_to "Edit this produto", edit_produto_path(@produto), class: "link back-button" %> |
  <%= link_to "Back to produtos", produtos_path, class: "link back-button" %>

  <%= button_to "Destroy this produto", @produto, method: :delete, class: "destroy-button" %>
</div>